# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'SKYWebView' do

    pod 'MBProgressHUD'
 
end
